name: marsec
description: "Aplicación educativa de ciberseguridad tipo Duolingo"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  lottie: ^2.6.0
  cupertino_icons: ^1.0.8
  http: ^1.3.0           # Dependencia para hacer peticiones HTTP
  flutter_dotenv: ^5.2.1   # Dependencia para manejar la clave API
  flutter_math_fork: ^0.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/marsec_logo.png
    - assets/images/marsec2_logo.png
    - assets/images/capitannn.png
    - assets/animations/success.json
    - assets/animations/failure.json
    - .env
