# .github/workflows/azure-static-web-apps.yml
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: >
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read

    steps:
      # 1. Checkout the repo
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # 2. Instala Flutter (canal stable)
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # 3. Cache de paquetes pub
      - name: Cache Pub Packages
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      # 4. Obtener dependencias (en el sub‑directorio de tu app)
      - name: Install dependencies
        working-directory: untitled1
        run: flutter pub get

      # 5. Generar la web
      - name: Build Flutter Web
        working-directory: untitled1
        run: flutter build web --release

      # 6. Instala el client OIDC para Azure SWA
      - name: Install OIDC Client
        run: npm install @actions/core@1.6.0 @actions/http-client

      # 7. Consigue el ID token de GitHub
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const core = require('@actions/core');
            return await core.getIDToken();
          result-encoding: string

      # 8. Despliega todo a Azure Static Web Apps
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_ROCK_09F99A41E }}
          action: upload
          app_location: "untitled1"           # Carpeta raíz de tu Flutter Web
          api_location: ""                     # vacío si no tienes Azure Functions
          output_location: "untitled1/build/web"  # Carpeta generada por flutter build web
          github_id_token: ${{ steps.idtoken.outputs.result }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          action: close
